name: First workflow

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First listing
        run: |
          pwd
          ls -lha
     
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Second listing
        run: |
          pwd
          ls -lha
      
      - name: Add Copyright at the end of index file
        run:
          echo "Copy 2025" >> index.html

      - name: Check if the Copyright is added
        run:
          cat index.html

