name: Deploy workflow
run-name: Deploy workflow

on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First listing
        run: |
          pwd
          ls -lha
     
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Second listing
        run: |
          pwd
          ls -lha
      
      - name: Add Copyright at the end of index file
        run:
          echo "Copy 2025" >> index.html

      - name: Check if the Copyright is added
        run:
          mkdir build && cp . build  
          cat ./build/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build
          path: ./build/

  deploy:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: my-build

    - name: Use artifacts
      run: |
        ls -lha
        cat ./build/index.html


